### ISSUE TITLE
[Bug?] inconsistency with "normal" lua intepreter

### ISSUE THREAD

**Issue by walksanatora** [MCJack123/craftos2-rom#12]
https://github.com/MCJack123/craftos2-rom/blob/016b633e3f00e96782d0f5a40b49f048dd887e06/bios.lua#L575 should be "rb" instead of "r"
(if i have to suggest in the CC:T repo i will)

**Comment by MCJack123** [comment]
This is a CC:T request, please make it there, and if it passes then it'll trickle down from upstream. (Though it's *highly* likely to be rejected since it'll break a large number of programs.)
